# Generated by Django 3.0.5 on 2020-04-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medfamilia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidades',
            new_name='Especialidade',
        ),
    ]
