# Generated by Django 3.0.5 on 2020-04-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medfamilia', '0004_auto_20200428_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidade',
            options={'ordering': ['titulo']},
        ),
    ]
