# Generated by Django 3.0.5 on 2020-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medfamilia', '0005_auto_20200429_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='respondida',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
