# Generated by Django 3.0.5 on 2020-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medfamilia', '0008_auto_20200429_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='respondida',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
