# Generated by Django 3.0.5 on 2020-04-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medfamilia', '0010_auto_20200429_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['respondida', 'id']},
        ),
    ]
