# Generated by Django 3.0.5 on 2020-05-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medfamilia', '0013_quemsomos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quemsomos',
            options={'verbose_name': 'Quem Somos', 'verbose_name_plural': 'Quem Somos'},
        ),
    ]
