# Generated by Django 3.0.5 on 2020-05-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medfamilia', '0014_auto_20200506_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quemsomos',
            options={'verbose_name': 'Quem Somos', 'verbose_name_plural': '01 - Quem Somos'},
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='missao',
            field=models.TextField(max_length=300, verbose_name='Missão'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='valores',
            field=models.TextField(max_length=300, verbose_name='Valores'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='visao',
            field=models.TextField(max_length=300, verbose_name='Visão'),
        ),
    ]
