# Generated by Django 3.0.5 on 2020-05-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medfamilia', '0015_auto_20200510_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['respondida', 'id'], 'verbose_name_plural': '03 - Consultas'},
        ),
        migrations.AlterModelOptions(
            name='especialidade',
            options={'ordering': ['nome'], 'verbose_name_plural': '02 - Especialidades'},
        ),
    ]
